engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
    - "src/"
exclude_paths:
  - "tests/"
  - "docs/"
  - "bin/"
  - "vendor/"